name: Deploy to QA

on:
  push:
    branches:
      - qa  # Deploy to QA when pushing to the 'qa' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Change to your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Deploy to QA
        env:
          NODE_ENV: qa  # Set the environment variable
        run: |
          cp .env.qa .env
          npm start  # or the appropriate command to deploy
