name: Deploy to Development

on:
  push:
    branches:
      - main  # Change this to your default branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Change to your Node.js version

      - name: Install dependencies
        run: npm ci

      - name: Deploy to Development
        env:
          NODE_ENV: development  # Set the environment variable
        run: |
          cp .env.dev .env
          npm start  # or the appropriate command to deploy
