name: Deploy to Production

on:
  push:
    branches:
      - prod  # Deploy to Production when pushing to the 'prod' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Change to your Node.js version

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci  # Use npm ci for faster installs

      - name: Deploy to Production
        env:
          NODE_ENV: production  # Set the environment variable
        run: |
          cp .env.prod .env
          npm start  # or the appropriate command to deploy

      - name: Verify Production Deployment
        run: |
          sleep 30  # Wait for the server to start
          curl -I http://your-production-server.com  # Replace with your production server URL
